kind: pipeline
type: docker
name: Sahil

steps:
- name : Repo clone  
  image: docker:git
  commands:    
     - git clone https://github.com/sahilmisri27/articles --branch master
     
trigger:
  branch:
    - master
  event:
    - push