kind: pipeline
type: docker
name: Sahil
on: [pull_request]

steps:
- name : Repo clone  
  image: docker:git
  commands:    
     - git clone https://github.com/sahilmisri27/articles --branch master
  settings:
    urls: https://ec2-3-145-9-201.us-east-2.compute.amazonaws.com/hook