name: Build Pull Request
on: [pull_request]

jobs:
  compile_job:
    name: Compile
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      steps:
- name : Articles clone  
  image: docker:git
  commands:    
     - git clone https://github.com/sahilmisri27/articles --branch master
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Change Execute Permission
        run: chmod a+x gradlew
      - name: Run Compile Source
        run: ./gradlew compileDebugSources 